INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Noah Joyce", "Tanlangco", "tanlangconoah@gmail.com", "639215712132");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Joshua Clement", "Millano", "jcpmillano@gmail.com", "639061479379");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Quenie Mae", "Millano", "maemillano@yahoo.com", "639065507414");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Loudeth", "Puyat", "loudettepuyat@gmail.com", "639161218081");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Charlotte", "Puyat", "charlotte.puyat@gmail.com", "639166612552");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Ryan-cel", "Lumagbas", "raelryenlumagbas@gmail.com", "639385718178");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jeany", "Lumagbas", "jeanylumagbas@gmail.com", "639203457579");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Almeus", "Almazan", "almeus.almazan@manilawater.com", "639171050411");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Joey", "Delos Santos", "joey.delossantos@manilawater.com", "639175080754");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Marjun", "Manahan", "marjun.manahan@manilawater.com", "639175024434");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Gerald", "Dimapilis", "gerald.dimapilis@manilawater.com", "639178295906");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Kevin", "Cangco", "kevinjulius.cangco@manilawater.com", "639178608052");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Ricson", "Cabigting", "ricson.cabigting@manilawater.com", "639175104889");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jonathan", "Sarsonas", "jonathan.sarsonas@manilawater.com", "639175160371");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Fermin", "Cristobal", "fermin.cristobal@manilawater.com", "639176208111");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jonathan", "Severo", "jonathan.severo@manilawater.com", "639175163105");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Clayton", "Ramil", "clayton.ramil@manilawater.com", "639175004285");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Marianne", "Navarro", "mariannenavarro1117@gmail.com", "639567223243");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Eliza", "Martinez", "eliza.martinez_20@yahoo.com", "639499976124");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Clarence", "Layba", "clarencelayba@gmail.com", "639177913079");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Alvin", "Selfaison", "alvin.selfaison@gmail.com", "639988532606");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Dave", "Martin", "dave.r.martin@gmail.com", "639162401930");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Russel", "Usi", "johnrusselusi@gmail.com", "639178940054");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Andrew", "Sy", "christopherandrewsy2018@gmail.com", "639957828056");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jan Vincent", "Santos", "jvbsantos@gmail.com", "639178133282");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("John Rema", "De Guzman", "refactoredeureka@gmail.com", "639563864184");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Pricilla", "Cacnio", "pricilla.cacnio@swapoolabs.com", "639064843061");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Marvin", "Labrador", "mr.marvinlabrador@gmail.com", "639952348903");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Mark", "Caguioa", "mgcaguioa@gmail.com", "639995709341");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Carlo", "Santos", "santos.carlo.a@gmail.com", "639178133292");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Gemmary Gem", "Dela Cruz", "gemmary08@gmail.com", "639276528497");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Christian", "Tacadena", "sirchverchoi@yahoo.com", "639238051799");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Analiza", "Bataller", "analizabataller@gmail.com", "639178065013");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Albert", "Reponcion", "albertreponcion001@gmail.com", "639458452157");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Kelvin", "Evangelista", "kelvinjhonevangelista04@gmail.com", "639176820504");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jerome", "Ancheta", "jeromecabico29@gmail.com", "639154418272");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jerico", "Ancheta", "stussyancheta@gmail.com", "639457204012");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Ronald", "Bolesa", "bolesaronald@gmail.com", "639335681938");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Tricia", "Bolesa", "triciabolano@gmail.com", "639424574736");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Rommel", "Alkuino", "alkuinorommel2000@yahoo.com", "639359481014");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Ricky Boy", "Martinez", "arbiemartinez@yahoo.com", "639758460387");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Reniel", "Marcelino", "reniel.marcelino10022@gmail.com", "639353113502");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Eden", "Dela Cruz", "edhz1128@gmail.com", "639325102792");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Gracie", "Cubacub", "grhaze1724@gmail.com", "639236797312");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Cherrie Joy", "Rosaldo", "cjrosaldo@gmail.com", "639161728768");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Patrick", "Cadacio", "pattycadacio01@gmail.com", "639550456430");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jhona", "Esparcia", "esparciajho@gmail.com", "639324883345");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jhury", "Poblete", "jhury.poblete@gmail.com", "639362379137");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jorimel", "Marcelino", "jorimel.marcelino03@gmail.com", "639068534901");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Diana", "Remoto", "dianalavide@gmail.com", "639554538641");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Tyrone", "Valdez", "tyrone.valdez@yahoo.com", "639393385404");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Reymark", "Sultan", "reymarg@gmail.com", "639197581195");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Fatima", "Cadacio", "fatima.cadacio@gmail.com", "639369424146");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Cristina", "Villamayor", "faithtinay@gmail.com", "639366347323");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Almond", "Manalo", "raquiztah.kamote@gmail.com", "639334452486");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Jovelyn", "Robles", "jovelynrobles@yahoo.com", "639264739012");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Arlene", "Manalo", "a.manalo801@gmail.com", "639332380148");
INSERT INTO jh_guests (first_name, last_name, email, mobile) Values ("Nathaniel", "Bancolita", "nathaniel.bancolita@manilawater.com", "639178906029");