INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Felix", "Tanlangco", "", "09076712550");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Cecilia", "Tanlangco", "", "09284937068");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Noah Joyce", "Tanlangco", "tanlangconoah@gmail.com", "09215712132");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Alexis Hanz", "Tanlangco", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Katherine", "Pagkaliwagan", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Delver", "Pagkaliwagan", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Xia Cemone", "Pagkaliwagan", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Xao Jacob", "Pagkaliwagan", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Sylvia", "Millano", "", "09279535910");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Mario", "Millano", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Joshua Clement", "Millano", "jcpmillano@gmail.com", "09061479379");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Quenie Mae", "Millano", "maemillano@yahoo.com", "09065507414");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Celia", "Lumagbas", "", "09994865325");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Cristina", "Lumagbas", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Loudeth", "Puyat", "loudettepuyat@gmail.com", "09161218081");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Marilou", "Puyat", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Celso", "Puyat", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Lawrence", "Puyat", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ashley", "Puyat", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Charlotte", "Puyat", "charlotte.puyat@gmail.com", "09166612552");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ryan-cel", "Lumagbas", "raelryenlumagbas@gmail.com", "09385718178");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jeany", "Lumagbas", "jeanylumagbas@gmail.com", "09203457579");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Rael", "Lumagbas", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ryen", "Lumagbas", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Anabel", "Luisaga", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Joanna", "Ramirez", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Almeus", "Almazan", "almeus.almazan@manilawater.com", "09171050411");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Joey", "Delos Santos", "joey.delossantos@manilawater.com", "09175080754");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Marjun", "Manahan", "marjun.manahan@manilawater.com", "09175024434");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Gerald", "Dimapilis", "gerald.dimapilis@manilawater.com", "09178295906");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Kevin", "Cangco", "kevinjulius.cangco@manilawater.com", "09178608052");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ricson", "Cabigting", "ricson.cabigting@manilawater.com", "09175104889");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jonathan", "Sarsonas", "jonathan.sarsonas@manilawater.com", "09175160371");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Fermin", "Cristobal", "fermin.cristobal@manilawater.com", "09176208111");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jonathan", "Severo", "jonathan.severo@manilawater.com", "09175163105");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Clayton", "Ramil", "clayton.ramil@manilawater.com", "09175004285");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Marianne", "Navarro", "mariannenavarro1117@gmail.com", "09567223243");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Eliza", "Martinez", "eliza.martinez_20@yahoo.com", "09499976124");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Nenita", "Cao", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Carlos", "Cao", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Arlene", "Guevarra", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Clarence", "Layba", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Alvin", "Selfaison", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Dave", "Martin", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Martin", "Backhaussen", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Russel", "Usi", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Andrew", "Sy", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jan Vincent", "Santos", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("John Rema", "De Guzman", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Pricilla", "Cacinio", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Marvin", "Labrador", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Mark", "Caguioa", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Analizza", "Gayoso", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Carlo", "Santos", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Cindy", "Bautista", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Emerald", "Layba", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Gemmary Gem", "Dela Cruz", "gemmary08@gmail.com", "09276528497");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Justine", "Enriquez", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Adelia", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jose", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jehannah", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jihrel", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Joan", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Teresita", "Tacadena", "", "09279694913");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Rose", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Romeo", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Aida", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Marvin", "Detera", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Gabriel", "Detera", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Lyra", "Detera", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Darvin", "Detera", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Myrna", "Detera", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Christian", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Cristine Joyce", "Tacadena", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Vannessa", "Magalong", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Virginia", "Branzuela", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Analiza", "Bataller", "analizabataller@gmail.com", "09178065013");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Edmond", "Guillang", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Albert", "Reponcion", "albertreponcion001@gmail.com", "09458452157");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Emelita", "Doctora", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Grace", "Antonil", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Teresita", "Cristobal", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Paolo", "Laroya", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Sherwin Lloyd", "Viceral", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Kelvin", "Evangelista", "kelvinjhonevangelista04@gmail.com", "09176820504");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jeremy", "Ancheta", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Lourdes", "Ancheta", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jerome", "Ancheta", "jeromecabico29@gmail.com", "09154418272");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Hilario", "Ancheta", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jerico", "Ancheta", "stussyancheta@gmail.com", "09457204012");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ronald", "Bolesa", "bolesaronald@gmail.com", "09335681938");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Tricia", "Bolesa", "triciabolano@gmail.com", "09424574736");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Rommel", "Alkuino", "alkuinorommel2000@yahoo.com", "09359481014");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ricky Boy", "Martinez", "arbiemartinez@yahoo.com", "09758460387");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Reniel", "Marcelino", "reniel.marcelino10022@gmail.com", "09353113502");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Aileen", "Blanca", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Roselyn", "Remoto", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Leizzle", "Rosaldo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Eden", "Dela Cruz", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Gracie", "Cubacub", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Zoilo 2", "Roque", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Zoren", "Roque", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ria", "Evasco", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Rolinda", "Rosaldo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Manuel", "Rosaldo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Reymundo", "Bonza", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Christine", "Rosimo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Cherrie Joy", "Rosaldo", "cjrosaldo@gmail.com", "09161728768");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Patrick", "Cadacio", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jhona", "Esparcia", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jhury", "Poblete", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jorimel", "Marcelino", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Diana", "Remoto", "dianalavide@gmail.com", "09554538641");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Tyrone", "Valdez", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Reymark", "Sultan", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Fatima", "Cadacio", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Cristina", "Villamayor", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Manuel", "Rosaldo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Almond", "Manalo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Patrick", "Rosimo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Lyn", "Rondilla", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jovelyn", "Robles", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Zisa", "Blanca", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Arlene", "Manalo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jason", "Flores", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jeselle", "Sosa", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Loann", "Apostol", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Benet", "Malaiba", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ferdinand", "Cervantes", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Chris", "Budikey", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Jessie", "Magno", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Dionisio", "Puyat", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Crisencia", "Pantalunan", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Dennis", "Puyat", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Richard", "Gabaon", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Manuel", "Lumanog", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Fatima", "Sedo", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Edward", "Cruz", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Mariano", "Cresencio", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Elena", "Detera", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Rosie", "Roque", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Arnie", "Liwanag", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Ryc", "Evasco", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Rosalinda", "Roque", "", "");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Nathaniel", "Bancolita", "nathaniel.bancolita@manilawater.com", "09178906029");
INSERT INTO jh_guests (id, first_name, last_name, email, mobile) Values ("Noel", "Dayao", "", "");